# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDUwOTIxOGNiNWUyOGNkODliZDlmZTc4NGE5ODJiYjYzOWZjNjhiN2Y0YmU0OThiMGNiYTI2MWZhNTUyNmQzOWRhN2I5M2I1YzlkMmNjODc0NTk3ZWFmOGM0OTljYjk3NDEwNWVmYTdlY2VmOGM1NTAxNWM5MzNmZDQ0YjViOGY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
